### ISSUE TITLE
Повертайся до Junior Army

### ISSUE THREAD

**Issue by dmitroshi** [oplotDev/Fluent-Pack#1]
Привіт. Учора такий заходжу на сервер, а тебе вже немає.. Може щось сталося? Якщо тобі не сподобалось щось чи хтось, то ти завжди можеш написати нам - ми відповімо. Ти дуже потрібен організації, так як таких професіоналів у розробці сайтів я ще не бачив (оптимизація просто каїф).

**Comment by oplotDev** [comment]
Я вернусь, але пізніше

**Comment by oplotDev** [comment]
Десь перед зимою

**Comment by dmitroshi** [comment]
сумно, без тебе ми поки що не дуже добре справляємося

**Comment by oplotDev** [comment]
у вас же є інший дизайнер

**Comment by dmitroshi** [comment]
сайти то він не робить..

**Comment by oplotDev** [comment]
rendick є

**Comment by dmitroshi** [comment]
У нас з'явився актуальний проєкт, для якого дуже потрібен сайт. Я впевнений, що ти його зробиш дуже швидко та якісно

**Comment by oplotDev** [comment]
мені треба спочатку завершити всі свої борги по проектам, тоді я мабуть вернусь

**Comment by dmitroshi** [comment]
брух, добре, тоді будемо чекати

**Comment by dmitroshi** [comment]
це посилання на проєкт, може тобі сподобається та захочеш допомогти https://www.figma.com/file/dFarA3KHv9ONHUVSgtI9Je/Untitled?node-id=0%3A1&t=jSJUYUU8kCeftj5O-1
